[package]
name = "price-split"
version = "0.1.0"
authors = ["Alexander Tchitchigin <sad.ronin@gmail.com>"]

[dependencies]
rand = "*"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
